services:
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - ./data:/var/lib/influxdb2
      - ./config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=root
      - DOCKER_INFLUXDB_INIT_PASSWORD=P!ssw0rd
      - DOCKER_INFLUXDB_INIT_ORG=arise
      - DOCKER_INFLUXDB_INIT_BUCKET=k6
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana

  k6:
    image: chatchawan.s/k6
    build: 
      context: ./
      dockerfile: Dockerfile
    environment:
      - K6_INFLUXDB_ORGANIZATION=arise
      - K6_INFLUXDB_BUCKET=k6
      - K6_INFLUXDB_TOKEN=NEnr0G7fAGee6SlP0ZqyaChwuCfBuqapDlaikpZg9Yvs9O4_oaCzU3r4dzFJedhqwXbSZpCRljNkxh8w_LsKeQ==
      - K6_INFLUXDB_ADDR=http://influxdb:8086
    volumes:
      - ./scripts:/scripts
    # command: "./k6 run /scripts/script.js -o xk6-influxdb"
    command: "./k6 run /scripts/script.js --out csv=/scripts/results.csv -o xk6-influxdb"